__version__ = "1.0.0"
__data__ = "2024-12-20"
__author__ = "Muhammad Bilal Khan"
__github_handle__ = "Hi-kue"
__description__ = "AI routes (inference, modal) for the pentagram-ai project."
__license__ = "GPLv3"
